 <!-- section:page footer -->
            <section id="page-footer">
                
                <!-- start:container -->
                <div class="container">
                    
                    <!-- start:foot-menu -->
                    <nav id="foot-menu" class="hidden-xs">
                    <ul id="menu-main-menu-2" class="nav clearfix"><li class="options"><a href="#" class="scrollToTop">Back to top <span class="glyphicon glyphicon-chevron-up"></span></a></li></ul>                       
                    </nav>
                    <!-- end:foot-menu -->
                    
                    <div class="foot-widgets row">

    <!-- start:col -->
    <div class="col-sm-4">
        <aside id="text-2" class="widget widget_text clearfix">         <div class="textwidget">
        <img class="flexible" src="<?php echo base_url('uploads/logo-nissan-foot.png');?>">
<hr>
<div class="kontak">
<?php echo $set->callnumber;?><br>
<?php echo $set->address;?>
</div>
</div>
        </aside>    </div>
    <!-- end:col -->
    
    <!-- start:col -->
    <div class="col-sm-4">
        <aside id="text-3" class="widget widget_text clearfix">
            <header><h2>Nissan Tegal</h2><span class="borderline"></span></header>          
            <div class="textwidget">
                <?php echo $set->front_text;?>
            </div>
        </aside>    </div>
    <!-- end:col -->
    
    <!-- start:col -->
    <div class="col-sm-4">
    <br>
        <header><h2>Visitor</h2></header>
        <span class="borderline"></span>
        <!-- Histats.com  START  (standard)-->
<script type="text/javascript">document.write(unescape("%3Cscript src=%27http://s10.histats.com/js15.js%27 type=%27text/javascript%27%3E%3C/script%3E"));</script>
<a href="http://www.histats.com" target="_blank" title="stats counter" ><script  type="text/javascript" >
try {Histats.start(1,3318307,4,408,270,55,"00011111");
Histats.track_hits();} catch(err){};
</script></a>
<noscript><a href="http://www.histats.com" target="_blank"><img  src="http://sstatic1.histats.com/0.gif?3318307&101" alt="stats counter" border="0"></a></noscript>
<!-- Histats.com  END  -->
    </div>
    <!-- end:col -->

</div>
<!-- end:row -->                    
                    <!-- start:row -->
                    <div class="copyright row">
                        <!-- start:col -->
                        <div class="col-sm-6">
                        &copy; <a href="#">Nissan Tegal</a> 2016. All rights reserved.                        </div>
                        <!-- end:col -->
                        <!-- start:col -->
                        <div class="col-sm-6 text-right">
                            Powered by  <a href="http://de-software.com" target="_blank">DE SOFTWARE INDO</a>                        </div>
                        <!-- end:col -->
                    </div>
                    <!-- end:row -->
                    
                                        
                </div>
                <!-- end:container -->
                
            </section>
            <!-- end:page footer -->
            
        </div>
        <!-- end:page inner wrap -->
    <div id="mm-blocker" class="mm-slideout"></div></div>
    <!-- end:page outer wrap -->

    <!-- start:wp_footer -->
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/jquery.mousewheel.js');?>"></script>
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/jquery.jscrollpane.min.js');?>"></script>
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/jquery.dop.ThumbnailGallery.js');?>"></script>
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/bootstrap.min.js');?>"></script>
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/mip.external.js');?>"></script>
<script type="text/javascript">
/* <![CDATA[ */
var miptheme_ajax_url = {"ajaxurl":"http:\/\/localhost\/decms\/themes\/nissan\/admin-ajax.php"};
/* ]]> */
</script>
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/functions.js');?>"></script>
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/js_composer_front.js');?>"></script>
<script type="text/javascript" src="<?php echo base_url('assets/themes/nissan/js/comment-reply.min.js');?>"></script>
<script>                                    </script>
<!-- JS generated by theme -->


    <script>
        "use strict";
        var miptheme_ajaxpagination_timer = 1000;
    </script>
    
    <!-- end:wp_footer -->
    

<div id="pbOverlay"><input type="checkbox" id="pbThumbsToggler" checked="" hidden=""><div class="pbLoader"><b></b><b></b><b></b></div><div id="pbPrevBtn" class="prevNext"><b></b></div><div id="pbNextBtn" class="prevNext"><b></b></div><div class="pbWrapper"><img><div></div></div><div id="pbCloseBtn"></div><div id="pbAutoplayBtn"><div class="pbProgress"></div></div><div id="pbCaption"><label for="pbThumbsToggler" title="thumbnails on/off"></label><div class="pbCaptionText"><div class="title"></div><div class="counter"></div></div><div class="pbThumbs"></div></div></div><iframe id="rufous-sandbox" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="true" style="position: absolute; visibility: hidden; display: none; width: 0px; height: 0px; padding: 0px; border: none;"></iframe></body></html>